name: Build

on:
  push:
    branches: ["master"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Pixeldrain Api Client
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: Fornaxian/pixeldrain_api_client
          path: pixeldrain_api_client

      - name: Checkout  Util
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: Fornaxian/util
          path: util

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install Deps
        run: |
          npm install --save-dev vite rollup tslib svelte @babel/preset-env rollup-plugin-svelte @rollup/plugin-node-resolve @rollup/plugin-commonjs rollup-plugin-livereload @rollup/plugin-terser @rollup/plugin-babel @rollup/plugin-typescript svelte-preprocess
 
      - name: Build
        run: |
          go get fornaxian.tech/pixeldrain_web/webcontroller
          go mod download fornaxian.tech/util
          go run main.go
          cd svelte && npm run build

      - name: Tree
        run: |
          tree

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Configure Pages
        uses: actions/configure-pages@v5.0.0
        with:
          static_site_generator: sveltekit
