name: Build

on:
  push:
    branches: ["master"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Build
        run: |
          cd svelte && npm run build
