name: Build

on:
  push:
    branches: ["master"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Install Deps
        run: |
          npm install --save-dev vite rollup tslib svelte @babel/preset-env rollup-plugin-svelte @rollup/plugin-html @rollup/plugin-node-resolve @rollup/plugin-commonjs rollup-plugin-livereload @rollup/plugin-terser @rollup/plugin-babel @rollup/plugin-typescript svelte-preprocess
 
      - name: Build
        run: |
          go get fornaxian.tech/pixeldrain_web/webcontroller
          go mod download fornaxian.tech/util
          go run main.go
          cd svelte && npm run build && npm run dev

      - name: Upload all files as artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: Website
          path: ./*

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Configure Pages
        uses: actions/configure-pages@v5.0.0
