name: Build

on:
  push:
    branches: ["master"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Deps
        run: |
          npm install
          npm install --save-dev vite rollup tslib svelte @babel/preset-env rollup-plugin-svelte @rollup/plugin-node-resolve @rollup/plugin-commonjs rollup-plugin-livereload @rollup/plugin-terser @rollup/plugin-babel @rollup/plugin-typescript svelte-preprocess
          npm run build --if-present
          npm run test --if-present
 
      - name: Build
        run: |
          cd svelte && npm run build
          tree

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
        with:
          static_site_generator: sveltekit
